MBA fixes - AMD
intel/intel-cmt-cat pull request #193
Opened 2021-08-23 20:16 UTC by babumoger

Couple of fixes.
1. MBA feature was broken for AMD
2. Changed printing messages from SOCKET to Core Complex for AMD
 
## Description

The MBA feature was not working when trying to set the MBA limits on AMD.
....
# pqos -I OS -e mba:1=0xf
NOTE:  Mixed use of MSR and kernel interfaces to manage
       CAT or CMT & MBM may lead to unexpected behavior.
ERROR: Expected MBA controller but not requested!
SOCKET 0 MBA COS1 - FAILED!
Allocation configuration error!
```
The code was using the hard coded value to detect the feature. Changed it to use the vendor specific mba_max values while detecting the feature.

Also fixed printing  messages on AMD.
Before the change.
SOCKET 0 MBA COS1 => 256% requested, 256% applied
SOCKET 1 MBA COS1 => 256% requested, 256% applied
SOCKET 2 MBA COS1 => 256% requested, 256% applied
SOCKET 3 MBA COS1 => 256% requested, 256% applied

After the change.

Core Complex 0 MBA COS1 => 256 requested, 256 applied
Core Complex 1 MBA COS1 => 256 requested, 256 applied
Core Complex 2 MBA COS1 => 256 requested, 256 applied
Core Complex 3 MBA COS1 => 256 requested, 256 applied

## Affected parts

- [x] library
- [x] pqos utility
- [ ] rdtset utility
- [ ] other: (please specify)

## Motivation and Context

Without this fix MBA feature wont work on AMD.

## How Has This Been Tested?

Tested on AMD system.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-08-31 08:14 UTC, aleksinx requested changes

2021-08-31 08:14 UTC, aleksinx commented on lib/os_cap.c
> +                                fprintf(fd, "MB:0=%d\n", vconfig->mba_max * 2);
Compilation warning
`os_cap.c:683: warning: %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.`
```suggestion
                                fprintf(fd, "MB:0=%u\n", vconfig->mba_max * 2);
```

2021-08-31 08:14 UTC, aleksinx commented on pqos/alloc.c
> +                        package = "Core Complex ";
Please remove redundant space
```suggestion
                        package = "Core Complex";
```

2021-08-31 08:14 UTC, aleksinx commented on pqos/alloc.c
> +                        package = "SOCKET ";
Please remove redundant space
```suggestion
                        package = "SOCKET";
```

2021-09-02 09:30 UTC, aleksinx requested changes

2021-09-02 09:30 UTC, aleksinx commented on pqos/alloc.c
> +                        package = "Core Complex ";
```suggestion
                        package = "Core Complex";
```

2021-09-02 09:30 UTC, aleksinx commented on pqos/alloc.c
> +                        package = "SOCKET ";
```suggestion
                        package = "SOCKET";
```

2021-09-07 19:17 UTC, babumoger commented
Addressed all the comments.  Let me know if I missed something. Thanks

2021-09-10 19:59 UTC, babumoger commented
Sent new pull request https://github.com/intel/intel-cmt-cat/pull/196 to address all the comments. I will close this pull request.

2021-09-20 16:54 UTC, closed without merging